### ISSUE TITLE
Error New-PartnerAccessToken

### ISSUE THREAD

**Issue by Flodu31** [microsoft/Partner-Center-PowerShell#100]
Hello,
I've the following error, on PowerShell Core 6.1.3, when I do a New-PartnerAccessToken:

> PS /Users/florentappointaire> $token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -TenantId $tenantId
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CGU86NNCU to authenticate.
New-PartnerAccessToken : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 3c4b1f54-8923-42dc-ad02-99241e28f900
Correlation ID: d3c5889e-cee7-4cac-9495-81eefa88e600
Timestamp: 2019-03-14 10:03:37Z
At line:1 char:10
$token = New-PartnerAccessToken -Consent -Credential $credential -Res ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], AuthenticationException
FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.AuthenticationException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken

I've not problem when I do an az login, so my credentials work fine.

Furthurmore, the following documentation is not Up-To-Date: https://docs.microsoft.com/en-us/partner-center/develop/partner-center-authentication?tabs=powershell-app-only%2Cpowershell-partner-consent%2Cpowershell-csp-auth%2Cdotnet-cpv-auth#app--user-authentication
The -ServicePrincipal option is not present in the last version of the module, but it asked for the TenantId.

Any idea?
Thanks.
Florent

**Comment by slavizh** [comment]
Can confirm the same. Works fine on PS 5.1 and PartnerCenter module.

**Comment by Flodu31** [comment]
Up, can we have an update from Microsoft please? Thanks

**Comment by isaiahwilliams** [comment]
Hi @Flodu31, 

Thank you for bringing this to our attention. I will work on getting the documentation update this week. With respect to the error you are encountering, it is being caused because the device code flow is being leveraged with the PartnerCenter.NetCore module. That flow does not support Azure AD web applications, and we currently do not have a way to interactively handle the login with this version of the module. We are actively exploring our options to unblock this exact scenario. Until then you can either utilize an Azure AD native application for this process, or generate the refresh token using the PartnerCenter module running on Windows.

**Comment by isaiahwilliams** [comment]
All of the documentation has been updated. Please let us know if there are any other concerns or questions.
