### ISSUE TITLE
Connect-PartnerCenter with cred object

### ISSUE THREAD

**Issue by kemper451** [microsoft/Partner-Center-PowerShell#122]
The command:

Connect-PartnerCenter -ApplicationId "<appID>" -Credential <PSCredential object>

is no longer connecting to PartnerCenter.  This command is currently working properly in module build 1.0.1809.10.  

In build 1.5.1904.3, it throws the error: 

Connect-PartnerCenter : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Connect-PartnerCenter -ApplicationId '<appid> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-PartnerCenter], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Store.PartnerCenter.PowerShell.Commands.ConnectPartnerCe
   nter

If I leave off the -Credential parameter, it will open a credential prompt which allows me to successfully login interactively, which doesn't help me in automation.

**Comment by isaiahwilliams** [comment]
@kemper451 if you are specifying user credentials in `Credential` parameter then that functionality has been retired. This was done because multi-factor authentication will soon be required when accessing the Partner Center API. You can find an alternative solution for how to connect without interaction at https://docs.microsoft.com/powershell/partnercenter/secure-app-model

**Comment by isaiahwilliams** [comment]
Please let us know if you have any additional concerns or questions.
