### ISSUE TITLE
et-PartnerAzureRateCard shows System.Collections.Generic.Dictionary`2[System.Decimal,System.Decimal] in Rates

### ISSUE THREAD

**Issue by keijzerh** [microsoft/Partner-Center-PowerShell#126]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by keijzerh** [comment]
using;
$rateCard = Get-PartnerAzureRateCard
$exportpath = $home + "\Downloads\azuremeters.csv"
$rateCard.Meters | Export-Csv $exportpath 

will end up having System.Collections.Generic.Dictionary`2[System.Decimal,System.Decimal] in the rates part of the CSV file.

**Comment by isaiahwilliams** [comment]
This is expected due to the structure of the data. A new price list feature is under development that will work with the new Azure experience in the Cloud Solution Provider program. Eventually you will be able to use that to get the data in the exact format you need. Until then you will need to build out the line for the export.
