### ISSUE TITLE
Get-PartnerInvoiceLineItem for Azure

### ISSUE THREAD

**Issue by qbihay** [Microsoft/Partner-Center-PowerShell#14]
Hello,
Compare to the old module, the Get-PartnerInvoiceLineItem -InvoiceId xxxx-BillingProvider Azure -LineItemType UsageLineItems missed a lot of value.
example : SKU / includedQuantity / ListPrice / taxamout / postTaxTotal / chargetype / etc...
so with this command it's impossible to retrieve the azure part of the billing.

**Comment by isaiahwilliams** [comment]
Hi @qbihay, 

Since you are looking for invoice details try running the following command instead 

```powershell
Get-PartnerInvoiceLineItem -InvoiceId xxxx-BillingProvider Azure -LineItemType BillingLineItems
```

If you set the LineItemType parameter to UsageLineItems it will return the Azure usage records associated with the invoice instead of the charges. Let me know if this returns the data you are seeking.

**Comment by isaiahwilliams** [comment]
I am glad that everything is working as excepted now. If you have any other issues please let us know.
