### ISSUE TITLE
Support for Customer Agreement

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#148]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Customer Agreement signing is already available in Sandbox. We need to first test this in Sandbox but this functionality is not available in the module. When this feature will be available?

**Describe the solution you would like**
We want to be able to get the details about customer agreement via cmdlet and being able to sign customer agreement via cmdlets in similar way we can for customer agreements

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**

**Comment by isaiahwilliams** [comment]
@slavizh we will be adding support for the Microsoft Customer Agreement in the next release. Right now the rough timeline for the upcoming release is the middle of September. Please note that the next release will contain a number of breaking changes, so we will be moving from version 1.5 to 2.0. 

A number of these breaking changes have to deal with authentication since all of the API operations are wrapped by the various cmdlets. I should have the [breaking changes](https://github.com/microsoft/Partner-Center-PowerShell/blob/master/docs/upcoming-breaking-changes.md) documentation updated by September 4, 2019 that way you will have an idea of what is changing.

**Comment by slavizh** [comment]
@isaiahwilliams Thanks! I will keep monitoring to understand what we will need to change. Hopefully if we use Refresh token should have to change the commands but not the authentication method.

**Comment by slavizh** [comment]
@isaiahwilliams ok. sounds like a few parameters added and a few changed for the auth part. Will give us a little work as I have to update that code in over 60 repositories that use that type of auth but hopefully it will be the last major change in auth for a few months.

**Comment by isaiahwilliams** [comment]
Version 2.0.1909.2 has been released and it includes support for the new agreements and addresses the authentication issues. Please let us know if you have any issues.
