### ISSUE TITLE
New-PartnerAccessToken  throws error for -UseDeviceAuthentication if web app instead of native app is used: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by morcinim** [microsoft/Partner-Center-PowerShell#169]
If -ApplicatonId points to a confidential client (web application) error will be thrown because 
New-PartnerAccessToken does not admit -Credential paramenter with -UseDeviceAuthentication switch.
The New-PartnerAccessToken with -UseDeviceAuthentication switch therefore only works if app is a public client (native app)

This logic is undocumented and possibly a bug as confidential clients are being recommended for implementing Secure Application Model in general.

# Steps to reproduce

PS C:\Users\morcinim> $token = New-PartnerAccessToken -ApplicationId $appId -Scopes https://api.partnercenter.microsoft.com/user_impersonation -Tenant $tenantId -UseDeviceAuthentication

WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code D8RNFN5HH to authenticate.
New-PartnerAccessToken : AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: c252087f-8a47-4029-844a-d93f641d3800
Correlation ID: 773a28fd-e5bf-46d9-91b3-ccf707ae8c3f
Timestamp: 2019-09-26 09:11:51Z
At line:1 char:10
+ $token = New-PartnerAccessToken -ApplicationId $appId -Scopes https:/ ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], MsalServiceException
    + FullyQualifiedErrorId : Microsoft.Identity.Client.MsalServiceException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken
  

## Expected behavior
Same as when ApplicationId refrerences **native** app:

PS C:\Users\morcinim> $token = New-PartnerAccessToken -ApplicationId f0ab7600-4dd1-yyyy-zzzz-f8527d4dxxxx -Scopes https://api.partnercenter.microsoft.com/user_impersonation  -Tenant $tenantId -UseDeviceAuthentication

WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DQUM484H3 to authenticate.

PS C:\Users\morcinim> $refreshToken = $token.RefreshToken 
PS C:\Users\morcinim> $azureToken = New-PartnerAccessToken -ApplicationId f0ab7600-4dd1-yyyy-zzzz-f8527d4dxxxx  -RefreshToken $refreshToken -Scopes 'https://management.azure.com/user_impersonation'  -Tenant $customerTenantId
$graphToken = New-PartnerAccessToken -ApplicationId f0ab7600-4dd1-yyyy-zzzz-f8527d4dxxxx  -RefreshToken $refreshToken -Scopes 'https://graph.microsoft.com/.default'  -Tenant $customerTenantId

 
## Actual behavior

> What is the behavior observed?
When ApplicationId refrerences **web** app:

AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

## Environment

> Please share additional details about your environment.
> Version
Install-Module -RequiredVersion 2.0.1909.5 -Name PartnerCenter -AllowClobber -Scope CurrentUser -Force
Install-Module -RequiredVersion 6.13.1 -Name AzureRm -AllowClobber -Scope CurrentUser -Force
Install-Module -RequiredVersion 5.8.3 -Name AzureRm.profile -AllowClobber -Scope CurrentUser -Force

**Comment by cblackuk** [comment]
Makes sense to me, should be fixed!

**Comment by ehrnst** [comment]
I have this issue as well. Not sure when it occurred. Using a token acquired through REST directly works

**Comment by isaiahwilliams** [comment]
When you specify the `UseDeviceAuthentication` parameter you are telling the module to use device code authentication. This particular flow only supports a public client, which is commonly referred to as a native client. If you try to use a web application with this approach the client secret value, even if it is included in the contents when request an access token, will be ignored by Azure Active Directory.

With the release of Partner Center PowerShell 2.0 several changes were made to the authentication to ensure that the best solution for this particular problem would be available for PowerShell 5.1 and PowerShell Core. The default authentication behavior will launch a web browser (e.g. Edge, Chrome, etc.) where you can complete the request. This approach supports both a native and web application because it is leveraging the authorization code 

Since this is a limitation of the device code flow no changes can be added to this module to address the issue. If you are planning to use the `UseDeviceAuthentication` parameter and a custom Azure Active Directory application it must be a native application.

**Comment by morcinim** [comment]
Great, thank you for the explanation. It would be great to include a note in help file of New-PartnerAccessToken powershell command that UseDeviceAuthentication flag implies ApplicationId parameter has to point to a native app to avoid confusion.
