### ISSUE TITLE
Shouldn't breaking changes increase the major version of the module?

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#179]
I just saw this https://github.com/microsoft/Partner-Center-PowerShell/releases/tag/2.0.1911.1 and seems there are breaking changes. When properer version control will be implemented so we can plan better?

**Comment by isaiahwilliams** [comment]
@slavizh with respect to the recent release the major version was not changed because the change to the SDK was not considered a major change. Taking this into consider we felt it was best to leverage the same approach to the versioning for the PowerShell module. Moving forward the plan to more critically evaluate how best to version the module with respect to breaking change in dependencies. That way we can ensure you are prepared to make any significant changes.

**Comment by slavizh** [comment]
That is not the best approach. Look at Az module how they do that. When I update the PowerSHell module I am not updating the SDK, I am updating the PowerShell module. This means that I explicitly need to review every update as I see it as minor but there could be breaking changes. I beg you please do proper releases. This is not helping us as partners.

**Comment by isaiahwilliams** [comment]
@slavizh completely understand and moving forward we will evaluate the plan more critically to evaluate how best to handle versioning with respect to the module. I really appreciate the feedback that you have shared.

**Comment by isaiahwilliams** [comment]
Thank you for sharing this feedback. If you have any additional concerns or feedback please feel free to share the details with us.
