### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by montereyharris** [Microsoft/Partner-Center-PowerShell#19]
# Steps to reproduce
Connect-partnercenter with login dialog returns AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application from Azure AD when http://localhost/ is the reply url

**Comment by isaiahwilliams** [comment]
Hi @montereyharris,

We are working to simplify the authentication process. Currently it is more complex than we like. To address your issue please make sure you have performed the steps documented at https://github.com/Microsoft/Partner-Center-PowerShell#configure-azure-ad-native-app

**Comment by montereyharris** [comment]
That worked. May I suggest may be a script that runs and preps a provided Native App or creates one? So the instructions are run this script or just have the Partner Center team add the PowerShell well known uri to the Native Center App

**Comment by mattheuslee** [comment]
I'm not so sure if you can have a script can create a native app since that's kind of a catch 22 - you need a native app ID to authenticate with partner center to establish a connection in order to create a native app (also, as far as I'm aware there is no existing REST endpoint which creates a Partner Center native app).

I think the current configuration steps in the Readme are clear enough, but perhaps if we could add in some error handling to provide a link to the configuration steps along with the error message if this particular error is encountered, it would be even better.

**Comment by isaiahwilliams** [comment]
Hi @montereyharris and @mattheuslee, this is great feedback. I will see how best we can incorporate these recommendations into the module. Also, we are working to add the ability to use app only authentication which will simplify this process. Since you were able to authenticate, I am going to close this issue. Please let us know if you have any additional feedback! We really appreciate your willingness to help us make this module better!
