### ISSUE TITLE
Get-PartnerCustomer returned missing rights

### ISSUE THREAD

**Issue by bilalAchahbar** [microsoft/Partner-Center-PowerShell#210]
I run the command "Get-PartnerCustomer" 
With the credentials I used from Azure AD app registrations.
But I received following error code.
 `Get-PartnerCustomer : The supplied role does not have the rights to perform the requested operation.`

The rights the Azure app registration has are:
![image](https://user-images.githubusercontent.com/36499520/69741293-174ebc00-113b-11ea-92c5-1aaa0476ef16.png)

**Comment by isaiahwilliams** [comment]
@bilalAchahbar is the user account you authenticate with a member of the Admin Agents, Helpdesk Agents, or Sales Agents roles in Partner Center?

**Comment by bilalAchahbar** [comment]
Can you help me out here.
I authenticate with the azure AD app registration "that has the permissions you see above".
But I can only add users and not Azure AD applications to different roles in Partner Center Dashboard.

Or Do I need to add my own user to the Partner Center roles because I log with my own user if I want to get the refresh Token (with the app ID and app secret of the azure ad app registration)

**Comment by isaiahwilliams** [comment]
Since you are looking to authenticate using a refresh token, then I would recommend following the steps documented [here](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0). It will show you how you will used the application you created along with a user credential that has been assigned to the correct role in Partner Center to generate the refresh token.

**Comment by isaiahwilliams** [comment]
If you are still encountering issues please let us know.
