### ISSUE TITLE
Set-MailboxJunkEmailConfiguration fails when running through delegated admin

### ISSUE THREAD

**Issue by Shadoxity** [microsoft/Partner-Center-PowerShell#244]
Trying to set some trusted domains on a few tenants and it just fails completely through the delegated admin powershell to exchange online. Can get connected, can list mailboxes etc happily but cannot run this command.

get-Mailbox -ResultSize Unlimited | Set-MailboxJunkEmailConfiguration -TrustedSendersAndDomains @{Add='domain1.com','domain2.com','domain3.com'}

# Steps to reproduce

Connect to exchange online powershell via the new partner center secure application model access
Attempt to update junk email configuration.

## Expected behavior

Update the trustedsendersanddomainlist

## Actual behavior

Get errors of either
Index was outside the bounds of the array.
    + CategoryInfo          : NotSpecified: (:) [Set-MailboxJunkEmailConfiguration], IndexOutOfRangeException
    + FullyQualifiedErrorId : System.IndexOutOfRangeException,Microsoft.Exchange.Management.StoreTasks.SetMailboxJunkEmailConfiguration
    + PSComputerName        : outlook.office365.com

OR

Error on proxy command 'Set-MailboxJunkEmailConfiguration -Identity:'user@domain.com' -TrustedSendersAndDomains:@{'Add' = 'domaintotrust.com.au'} -Confirm:$False' to server ME4P282MB1029.AUSP282.PROD.OUTLOOK.COM: Server version 15.20.2581.0000, Proxy 
method PSWS: 
Cmdlet error with following error message:
Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: The operation couldn't be performed because 'user@domain.com' couldn't be found.

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
Latest version of partnercenter, exchangeonline, msonline powershell modules

**Comment by isaiahwilliams** [comment]
@Shadoxity unfortunately through this issue there is not any support that can be provided. I would recommend opening a support ticket through Partner Center because this appears to be an issue with Exchange Online that Microsoft support will be able to assist with.

**Comment by Shadoxity** [comment]
Hey @isaiahwilliams It may be a case of fixing the error messages in the partner center powershell.

I connected via the old delegated admin method and when running the command we now get a message back saying that delegated admin does not have permission to run that command.

So MS has changed what rights you need to run that I guess.

**Comment by isaiahwilliams** [comment]
@Shadoxity this module is not invoking the commands, but rather providing you with a way to generate the access token based on a refresh token. With how you are connecting this is not any different than what you have been doing in the past by creating a PSSession and then importing it. So, the error message you are receiving is actually from Exchange Online. 

There is a minor difference between connecting using MFA and delegated administrative privileges, but what is being done here is identical to the updated Exchange Online PowerShell available through the EAC.

**Comment by Shadoxity** [comment]
@isaiahwilliams 
Just saying, when running the command connected via the new partner center access token method, you do not get an error saying that delegated admin cannot run this, you just get the errors I provided.
If you connect with username/password to exchange online delegated admin, running hte same commands you get an error that you cannot run this as a delegated admin. So it obviously has some differences to not provide teh correct error message.

**Comment by isaiahwilliams** [comment]
@Shadoxity if you were use the module described in this [article](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps) you will get the same error. When you invoke the `Connect-ExoPSSession` it will do the following actions

1. Prompt you for first factor of authentication and then the second factor if MFA is enforced for the account being used
2. Generates an access token 
3. Create a new PSSession using the following connection URI https://outlook.office365.com/powershell-liveid?DelegatedOrg=customer-id-here&BasicAuthToOAuthConversion=true 

All of this tells the Exchange Online PowerShell endpoint that you are connecting using an access token instead of a password. This is different than what you mentioned above where you are connecting without doing the `BasicAuthToOAuthConversion`. This is the reason you are getting two different errors. 

While I agree with you the error message is not correct it is not something controlled through the Partner Center PowerShell module. I will share this information with the Exchange Online team, so they can investigate.
