### ISSUE TITLE
RE: #240 Exchange online powershell - Unable to get refresh token programatically and via a site

### ISSUE THREAD

**Issue by Shadoxity** [microsoft/Partner-Center-PowerShell#246]
https://github.com/microsoft/Partner-Center-PowerShell/issues/240#event-2911063963

This was closed prematurely

Hey @isaiahwilliams  That is my point,
The problem is generating the initial refresh token without having someone manually go into powershell and create it and then copy and paste it somewhere.

For the other partnercenter methods we can use the URL for our azure application to grant consent. How can we do a similar thing for exchange? I need to be able to programatically grant the consent and get the refresh token.

Please assist.

How can we perform this first part via a website or similar

**Comment by isaiahwilliams** [comment]
@Shadoxity with Exchange Online PowerShell you need to use a specific Azure AD application, that has all the correct configurations. Currently the only application with the correct configurations is the one used by the Exchange Online PowerShell module. All of this means partners cannot create an Azure AD application for generating access tokens for use with PowerShell. 

The good news here is that when you run `New-PartnerAccessToken -Module ExchangeOnlie` it is using the same application the Exchange Online PowerShell module. Which means it does not require consent or pre-consent. So, you can generate a single refresh token at the partner level and use it for requesting access tokens for all your customers scoped to Exchange Online.

**Comment by Shadoxity** [comment]
@isaiahwilliams 
Thats exactly my problem though, the only way to get the initial token is via a manual powershell command. We have an integration that is sold to MSP's and need to access this. And we typically collect this info through the web interface, but that seems to be impossible with the exchange module and the new secure application model.

Thats what I am struggling with right now.

**Comment by isaiahwilliams** [comment]
@Shadoxity the initial refresh token can be generated through a number of different methods. If you are interested in what the Partner Center PowerShell module is doing, then you can use a tool like Fiddler to see the exact API methods being invoked. 

Since you are looking for a way to do this outside of the Partner Center PowerShell module then I would recommend leveraging one of the following 

1. Microsoft partner benefits to get direct help with this development effort
2. Microsoft support
3. [Partner Center Security Guidance Group](https://www.microsoftpartnercommunity.com/t5/Partner-Center-Security-Guidance/ct-p/partner-center-security-guidance)

**Comment by isaiahwilliams** [comment]
If you have any other issues with the Partner Center PowerShell module please feel free to open a new issue.
