### ISSUE TITLE
Get-PartnerCustomerSubscriptionResourceUsage : The term 'Get-PartnerCustomerSubscriptionResourceUsage' is not recognized as the name of a cmdlet.

### ISSUE THREAD

**Issue by motim6026** [microsoft/Partner-Center-PowerShell#252]
When try run Get-PartnerCustomerSubscriptionResourceUsage command from  web console 
get this error message:
Get-PartnerCustomerSubscriptionResourceUsage : The term 'Get-PartnerCustomerSubscriptionResourceUsage' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-PartnerCustomerSubscriptionResourceUsage -CustomerId '1c4b710a-2a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-PartnerCustomer\u2026iptionResourceUsage:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundExcepti
![tempsnip](https://user-images.githubusercontent.com/27952544/71979091-8aad1880-3225-11ea-9717-69bf6e2c34a8.png)

**Comment by isaiahwilliams** [comment]
Since the Partner Center module is not installed with the default cloud shell you will need to run the following 

```powershell
Install-Module PartnerCenter
```

To avoid future confusion with this we have disable the try it feature for the documentation. This feature may be re-enabled in the future, but there are a few items that need to be worked through. I appreciate you taking the time to let us know about this issue.
