### ISSUE TITLE
IMPORTANT: Refresh token failing - AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor  authentication to access

### ISSUE THREAD

**Issue by Shadoxity** [microsoft/Partner-Center-PowerShell#259]
We have had partner center access start failing to get access tokens out of nowhere and no idea why!

# Steps to reproduce

Attempt to get an access token with a refresh token that was initially retrieved about 7 days ago with no changes made to the environment.

$token = New-PartnerAccessToken -ApplicationId $client_Id -Credential $credential -RefreshToken $refreshToken -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Tenant $Delegatedadminid

Gets the error New-PartnerAccessToken : AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must 
use multi-factor authentication to access 'fa3d9a0c-3fb0-42cc-9193-47c7ecd2edbd'.
Trace ID: aaf534ab-254b-4f2c-bf32-625fd335e600
Correlation ID: 235ad0f5-88dd-4268-b1c8-28a943068a42
Timestamp: 2020-01-14 20:30:08Z

$aadGraphToken = New-PartnerAccessToken -ApplicationId $client_Id -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.windows.net/.default' -ServicePrincipal -Tenant $Delegatedadminid

Error: New-PartnerAccessToken : AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must 
use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'.
Trace ID: ce3ac0c1-4681-4fb5-b7b0-ab8b2b0bd200
Correlation ID: aafb827b-a8a2-4944-a5c7-15e5de15688b
Timestamp: 2020-01-14 20:37:07Z
At line:1 char:18

$graphToken = New-PartnerAccessToken -ApplicationId $client_Id -Credential $credential -RefreshToken $refreshToken -Scopes 'https://graph.microsoft.com/.default' -ServicePrincipal -Tenant $Delegatedadminid

Error: New-PartnerAccessToken : AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must 
use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.
Trace ID: 32da93b5-d763-4a83-a958-2f06124bd400
Correlation ID: 7590b30a-cd3b-41d9-9a6a-49cf1b2b62a1
Timestamp: 2020-01-14 20:37:09Z

## Expected behavior

Access tokens retrieved and connect to partner center powershell

## Actual behavior

Commands fail - errors above. Should not be failing!
Unable to connect to partner center powershell, causing issues and caused a bunch of manual work required to fix this today.

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

Same error with partnercenter module 3.0.2 and 3.0.6

**Comment by Shadoxity** [comment]
Any insight into this?

**Comment by isaiahwilliams** [comment]
@Shadoxity I believe this particular error is a result of the multi-factor authentication enforcement. Are you still having issues?

**Comment by Shadoxity** [comment]
@isaiahwilliams The whole purpose of this secure application model is so that you can have MFA enabled and programatically access the resources!
So Why would that affect this?

More to the point, WHEN would that cause this issue, as this is a MASSIVE problem if we have gotten a bunch of refresh tokens so we can perform what we are being paid to do, and then all of a sudden we will no longer be able to access the resources and require someone to manually grant access again.

Please provide more info on why and when this would happen and what we have to do, cause it is unacceptable if Microsoft created the Secure Application Model for the purpose of securely access resources, and then they break the access by something (MFA) That this model was designed so that it could be turned on and not require it.

**Comment by isaiahwilliams** [comment]
@Shadoxity to expand on my comments above the most likely cause for this particular issues, since you implemented the secure application model, is that you were not challenged for multi-factor authentication when generating the initial refresh token. You will still get a valid refresh token that can be used to request access tokens. However, the resulting token will not have the expected MFA claim which will cause the AADTS50076 error to be encountered. Can you confirm that you were challenged for MFA when you generated the initial refresh token?

**Comment by Shadoxity** [comment]
@isaiahwilliams So are you saying if the admin account has MFA disabled when they grant access to the app, then enable MFA on the account, The token will then fail to work like above?

ANd can we be clear if that excludes a whitelisted IP (I.e. MFA is not prompted cause they accept it from a whitelisted IP).
I would test it, but I cannot disable MFA on our admin accounts.

**Comment by isaiahwilliams** [comment]
@Shadoxity you are correct. If the token was generated prior to multi-factor authentication being enforced, then you will encounter this particular error. Also, the use of conditional access (e.g. the feature that excludes thee requirement for MFA for particular IP range) can result in this particular error for partners. The reason I am making the partner distinction is that the partner security requirements are being enforced through Azure Active Directory and will be through Partner Center in the near future. So, if you are leveraging conditional access then there is a chance you might not be challenged for multi-factor authentication and that could result in errors like this due to the enforcement.

**Comment by isaiahwilliams** [comment]
If you have any additional questions regarding multi-factor authentication as it relates to the partner security requirements, then I would recommend posting them [here](https://www.microsoftpartnercommunity.com/t5/Partner-Center-Security-Guidance/ct-p/partner-center-security-guidance)

**Comment by j-nolan** [comment]
I had this error while using the azure CLI (`az`).
The fix for me was to run `az login`.

Posting here for others to find since this issue is one of the top results for "aaDSTS50076"

**Comment by jameskirsop** [comment]
@isaiahwilliams, sorry to dig up an old Issue, but can you expand on your comments a little more?

Eg. if Conditional Access is enabled and I generate a *new* refreshToken using:
```$Exchangetoken = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716' -Scopes 'https://outlook.office365.com/.default' -Tenant <tenant_id> -UseDeviceAuthentication```
should I expect it to work and not get the above error? I've tried to generate a new token, but I'm still getting the error described in the original issue report.

FWIW, I'm logging in from an 'Excluded location' from MFA (i.e. from our office)...

**Comment by Thadukaajay** [comment]
Please provide the exact error message (include Operation ID etc).
Answer: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.
Trace ID: 69166393-4cce-4d1e-b6e9-a4a4e8801d00
Correlation ID: 1645a184-dd60-44a6-a4e9-a1d201245714
Timestamp: 2023-08-17 16:38:51Z: The remote server returned an error: (400) Bad Request.

Question: Description
Answer: After MFA authentication is enabled. This failure occurs. we are not able re-authenticate it

**Comment by Shadoxity** [comment]
There is more to this, because we are seeing the issue occur on client tenants of a partner account.

Partner has MFA enabled and does MFA during the token prices but some client tenants will provide this error message while others do not.

Does the partner tenant need a new MFA for the refresh token of a client tenant has changes?
