### ISSUE TITLE
URGENT: Exchange module fails to connect for numerous tenants

### ISSUE THREAD

**Issue by Shadoxity** [microsoft/Partner-Center-PowerShell#263]
We are having access is denied failures to multiple customer tenants.
Using secure application model. We get an access token, we get a refresh token, but fails to connect.

This is happening for multiple customer tenants that we are a delegated partner admin for.
Some will connect and work, others will not!

# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior

> Share the expected output

## Actual behavior

New-PSSession : [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following error message : Access is 
denied. For more information, see the about_Remote_Troubleshooting Help topic.
At line:23 char:12
+ $session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionOpenFailed
Import-PSSession : Cannot validate argument on parameter 'Session'. The argument is null. Provide a valid value for the argument, and then try 
running the command again.
At line:25 char:18

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

Have tried partnercenter 3.0.5 and 3.0.2 same behaviour

**Comment by isaiahwilliams** [comment]
@Shadoxity it is difficult to say for certain what is happening here. I would recommend that you verify the access token you generated targets the customer. This is done by specifying the identifier of the customer when you create the access token using the New-PartnerAccessToken command using the tenant identifier.

**Comment by Shadoxity** [comment]
@isaiahwilliams The customer is targeted via their tenant ID.

We get this access is denied on random tenants in our partner center. What I am trying to find out it WHY this is being denied!

As we can click through them via the partner center, it should be working fine here.
Yet some work perfect, others give us access denied for no reason.

It clearly appears to be some fault in the MS system

**Comment by protocolist** [comment]
I have this problem with **all** tenants in our Partner Center, incorporating the example code [here](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0) as follows:

```powershell

$customers = Get-MsolPartnerContract -All
$exchangeToken = New-PartnerAccessToken -Module ExchangeOnline
$upn = "<snip>"

foreach ($customer in $customers) {

    $token = New-PartnerAccessToken -Module ExchangeOnline -RefreshToken $exchangeToken.RefreshToken  -Tenant $customer.TenantId

    $tokenValue = ConvertTo-SecureString "Bearer $($token.AccessToken)" -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential($upn, $tokenValue)

    $session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://outlook.office365.com/powershell-liveid?DelegatedOrg=$($customerId)&BasicAuthToOAuthConversion=true" -Credential $credential -Authentication Basic -AllowRedirection

}
```

For every tenant we receive a variation of:

`New-PSSession : [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following
error message :
[ClientAccessServer=SY4P282CA0010,BackEndServer=,RequestId=85f762d7-a81a-47df-b3da-7a1b1c5f1418,TimeStamp=2/10/2020
4:14:49 AM] Access Denied For more information, see the about_Remote_Troubleshooting Help topic.`

All of the other module functionality is working, everything is configured to the letter of the documentation.

**Comment by protocolist** [comment]
@isaiahwilliams @Shadoxity I seem to be having this problem with **all** tenants in our Partner Center, using module version 3.0.6.

My code is based on the [documentation](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0) (though it appears to have an error on line 2 or 5)

````powershell

$customers = Get-MsolPartnerContract -All
$exchangeToken = New-PartnerAccessToken -Module ExchangeOnline
$upn = "<snipped>"

foreach ($customer in $customers) {

    $customerId = $customer.TenantId

    $token = New-PartnerAccessToken -Module ExchangeOnline -RefreshToken $exchangeToken.RefreshToken  -Tenant $customerId 

    $tokenValue = ConvertTo-SecureString "Bearer $($token.AccessToken)" -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential($upn, $tokenValue)

    $session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://outlook.office365.com/powershell-liveid?DelegatedOrg=$($customerId)&BasicAuthToOAuthConversion=true" -Credential $credential -Authentication Basic -AllowRedirection

    #Import-PSSession $session
    #Exchange functionality todo
    #Remove-PSSession $session
}
````
For every tenant I receive a variant of the following:
`New-PSSession : [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following
error message :
[ClientAccessServer=SY3PR01CA0135,BackEndServer=,RequestId=30889285-2b86-42b0-b60e-22246670a106,TimeStamp=2/10/2020
4:37:41 AM] Access Denied For more information, see the about_Remote_Troubleshooting Help topic.`

Guidance or a fix would be immensely appreciated, all of our automation has gone dark :(

**Comment by Shadoxity** [comment]
@MicrosoftIssueBot @isaiahwilliams Can we get an update? Its a joke this is still not fixed. 
You want us to have MFA enabled, you want us to use the secure application model, but its all broken and its affecting our business.

**Comment by isaiahwilliams** [comment]
@protocolist and @Shadoxity I think it will be helpful to provide some context of what exactly is happening and how you can get support. Through the Partner Center PowerShell module you are generating an access token that will be used to create a PowerShell remoting session with Exchange Online. Using that token you are creating a new session as you have in the past, but since the `BasicAuthToOAuthConversion` query string parameter was specified the session will use an access token to connect instead of user credentials. The error you are encountering is from Exchange Online and there a handful of reasons why I believe it might be happening. To help isolate the issue it is important to verify the following 

1. You are connecting using an access token that was generated by an individual who has Admin Agent privileges
2. The customer in question has not removed the partner relationship which breaks your delegated administrative privileges 
3. If the customer in question was added using the reseller relationship request and the DAP query string parameter was set to false. This would result in a scenario where you do not have delegated administrative privileges over the customer
4. You are able to access the Exchange Admin Center without any error. Through my experience I have discovered minor issues delegated administrative privileges and Exchange. If you are unable to access the Exchange Admin Center for the customer, then you will need to open support ticket.

If the above does not help isolate the issue, please try connecting interactively using the process documented [here](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps#connect-to-exchange-online-powershell-by-using-mfa). This should result in the same access denied error, but having insight into whether or not this fails will be extremely help to completely rule out any PowerShell issues. In the event you are encountering the same error interactively and non-interactively, then please open a support ticket through Partner Center or leveraging your ASfP/PSfP agreement. There is an issue that will need to be investigated by the Exchange Online team.

**Comment by Shadoxity** [comment]
Hey @isaiahwilliams thanks for the info.

1. Yes my user has admin privileges and can access the customer tenant via partner center in the normal ways
2. Definitely not, the customer does not even have access to an admin user of their tenant
3. Has used the same as all our other customer tenants.
4. Yes fine.


Connecting through the connect-exopsession command, via my UPN it gets access denied. Via our partner global admin account it connects correctly!

What is the issue here? 

Partner center, my user account has "connects as an admin agent".

**Comment by isaiahwilliams** [comment]
@Shadoxity thank you for the additional information. This is an issue that needs to be addressed by the Exchange Online team. Leveraging a user with Admin Agent privileges should be more than sufficient because the Admin Agents group is mapped as a foreign principal object to the customer's global admin role. It should not be required that you leverage a user in the partner tenant that has additional privileges because the operations are being performed against a customer. 

Taking all of this into consideration I would recommend that you open a support ticket either through Partner Center or using your support agreement with Microsoft. That way the Exchange Online team can help investigate to determine what exactly is happening here.
