### ISSUE TITLE
New-PartnerAccessToken throws error on Linux and PowerShell core 6.X.X

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#265]
# Steps to reproduce

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

The error is:

```
New-PartnerAccessToken : Unable to load shared library 'libsecret-1.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsecret-1.so.0.so: cannot open shared object file: No such file or directory
```

Is there some undocumented dependencies on linux?

## Expected behavior

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by LeonJansen** [comment]
Same error here:
![image](https://user-images.githubusercontent.com/4737467/72888187-66fdce00-3d0d-11ea-9d3b-9d0ee5b85df8.png)


`Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0`

**Comment by isaiahwilliams** [comment]
This issue is related to the [extension should not crash on Linux if LibSecret 1.so.0 is not present](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/issues/56) issue. You can resolve it by installing `libsecret-1-dev`, however, this will not resolve the issue with the refresh token generation

**Comment by slavizh** [comment]
@isaiahwilliams so could these dependencies be documented somewhere. For example I do not know if there are more cmdlets that require some library as the error is generated when the cmdlet is executed.

**Comment by isaiahwilliams** [comment]
@slavizh that is the only dependency that is not self contained. It is my understanding the Azure Active Directory team is planning to address this particular issue. Once they do we will get the library updated, so this will not be an issue after that point. Until then we are exploring the best option here because there is one remaining item that needs to be resolved.

**Comment by isaiahwilliams** [comment]
Since this particular issue is related to #266 I am going to close this particular issue. All updates being made on this front will be tracked under the other issue.
