### ISSUE TITLE
When we use Refresh token to login to Azure we cannot Set PAL

### ISSUE THREAD

**Issue by slavizh** [microsoft/Partner-Center-PowerShell#277]
# Steps to reproduce
Hi,
When we use refresh token and we login to Azure via Az PowerShell Partner Admin Link cannot be set. The error that I get:

```
'Operation failed with message 'The user does not have an account in this tenant, work with the administrator to add the account. If you are a CSP partner logged in the customer tenant, you will not be able to link the Partner ID''.
```

Is this by design or I am not doing something correctly? If you do not know where is the right way to ask about this?

**Comment by isaiahwilliams** [comment]
@slavizh I have encountered the error before using the Az module and partner level user credentials. Based on my understanding this is expected because as the providing partner you cannot configure Partner Admin Link. I could be incorrect on this, so I would recommend connecting with Microsoft support to see if they can confirm this for you.

**Comment by slavizh** [comment]
ok. closing.
