### ISSUE TITLE
How do I authenticate to PartnerPortal properly?

### ISSUE THREAD

**Issue by artisticcheese** [microsoft/Partner-Center-PowerShell#287]
I'm confused what I shall be used for automation purpouses when working with partner center API through powershell. Per documentation (https://docs.microsoft.com/en-us/powershell/partnercenter/authenticate?view=partnercenterps-3.0) you have an option to authenticate with serviceprincipal which works for me but end up with "Unauthorized access" when calling "Get-PartnerCustomer". Another article (https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0) calls for more complicated setup with some refresh tokens, consents, expiring things in 90 days etc. My ultimate goal to automate certain things through Powershell in partner portal but I'm confused what technologies shall I use for authenticating and performing actions.

**Comment by isaiahwilliams** [comment]
Due to the requirement for multi-factor authentication and not all operations supporting app only authentication, you will need to leverage the Secure Application Model. This is where you will perform an interactive authentication once, and then use the generated refresh token moving forward instead of user credentials. Note the refresh token does expire every 90 days, however, when you request a new access token there is a new refresh token returned as well. So, you can design your own process to update the securely store refresh token on a set interval or you can update it manually every 90 days.
