### ISSUE TITLE
Can not login with serviceprincipal to tenant subscriptions

### ISSUE THREAD

**Issue by artisticcheese** [microsoft/Partner-Center-PowerShell#288]
# Steps to reproduce
I have serviceprincipal which is part of `AdminAgents` group which supposed to have Owner permissions to all subscriptions in our CSP portal. When I try to set context to any of the customers it gets error below. This works fine if I authenticate with my user account but fails with serviceprincipal even though we are part of the same `AdminAgents` group

```
Connect-AzAccount -ServicePrincipal -Credential $pscredential -TenantId $tenantID
PS C:\repo\virtualDatacentre\scripts> Set-AzContext -SubscriptionId $subscription.SubscriptionId -TenantId $partner.CustomerId
Set-AzContext: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant.
```

## Expected behavior

Able to list resources in subscription of partner

## Actual behavior

Getting error ` The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant`

## Environment

PS C:\repo\virtualDatacentre\scripts> get-module PartnerCenter

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.7                 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-PartnerCenter…}
```

**Comment by isaiahwilliams** [comment]
What you have done is configured the service principal for pre-consent. While this has benefits, it unfortunately will not make it where you can access an Azure subscription using app only (service principal) authentication. You will need to explicitly assign the service principal permissions over the subscription.

**Comment by artisticcheese** [comment]
This does work with normal user accounts though by just being part of `AdminAgents` group. I assumed permissions are being assigned based on membership inside above mentioned group. It's not the case? How do I automate then process if I have hundreds of customers and each of them multiple subscriptions

**Comment by isaiahwilliams** [comment]
You are correct having a service principal in the AdminAgents group does not grant it permissions over an Azure CSP subscription. My recommendation would to be to leverage user credentials, so you do not explicitly have to grant the service principal permissions. See [Add or remove role assignments using Azure RBAC and Azure PowerShell](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-powershell) for more information. 

If you have any issues with this I would recommend opening an issue on the Azure documentation, since this functionality is out of scope for the Partner Center PowerShell module.
