### ISSUE TITLE
A parameter cannot be found that matches parameter name 'ServicePrincipal'.

### ISSUE THREAD

**Issue by skille** [Microsoft/Partner-Center-PowerShell#39]
Unable to connect with Access Token with your documentation:

CMD: New-PartnerAccessToken -Credential $Credential -TenantId $TenantID -ServicePrincipal
Error: New-PartnerAccessToken : A parameter cannot be found that matches parameter name  'ServicePrincipal'.

**Comment by isaiahwilliams** [comment]
Hi @skille, 

The required changes to address this issue are currently being reviewed. With this said this issue will be resolved with the next release. You can work around the issue for now by removing the ServicePrincipal parameter. Since you are including the TenenatId parameter the command will know you are using app only authentication.

**Comment by isaiahwilliams** [comment]
Hi @skille, 

This issue has been addressed with [1.5.1811.4](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1811.4). Please let us know if you encounter any other issues.
