### ISSUE TITLE
Differnet results between PowerShel and Automation Module

### ISSUE THREAD

**Issue by VaperWare** [Microsoft/Partner-Center-PowerShell#53]
When I run my script in PowerShell with this command in it, Get-PartnerCustomerSubscriptionUtilization, I receive a summary total of 64,151.69 and when I run the exact same code as an Azure Automation job I receive a summary total of 61,940.90.

Why would this be?

Module information
Azure Module - PartnerCenter - 1.5.1812.1
Azure PowerShell - PartnerCenter  - 1.5.1812.1

TIA
Gerald

**Comment by isaiahwilliams** [comment]
Hi @VaperWare, 

There are a number of reasons this could happen. Just to confirm you are using the same UTC timestamps in both tests?

**Comment by VaperWare** [comment]
Isaiah, thanks for the reply.  Yes, the same code and same parameters are used in both scripts.  Here's the are the time formats.

$StartTime = (get-date ((Get-Date $StartDate -Format o).Split("T")[0].ToString() + " 00:00:00")).ToUniversalTime()

$EndTime = (get-date ((Get-Date $EndDate -Format o).Split("T")[0].ToString() + " 23:59:59")).ToUniversalTime()

**Comment by isaiahwilliams** [comment]
Hi @VaperWare, 

The results should match when performing this type of operation. If your end date is a time in the future, then there is a possiblity you will find more records each time the query is invovked. Also, there is a chance that utilization records might be late. So, you are finding more because the late records are being emitted. If you are still experincing this issue with a past period then please let us know and we can investigate further.
