### ISSUE TITLE
Download reconciliation file

### ISSUE THREAD

**Issue by AleixPerez** [Microsoft/Partner-Center-PowerShell#56]
# Feature Request

I need to automate the billing process for all tenants in our CSP, but every month I have to download reconfile, filter it and resend to each Service Manager to put the markup.

For that I'm trying to automate the process, but I can't download the information that gives me the reconfile for the IUR subscriptions, for the tenants I don't have the problem, because I can get the information with the "Get-PartnerCustomerServiceCosts" cmdlet, but for IUR i can't found any cmdlet that give me this information.

Can you say me if is possible download the entire reconfile or access to this information directly from any cmdlet in the scripting prespective?

Thank in advance

kind Regards

**Comment by isaiahwilliams** [comment]
Hi @AleixPerez,

The Partner Center API does not currently provide the ability to download the reconiliation file. However, you can utilize the [Get-PartnerInvoiceLineItem](https://docs.microsoft.com/powershell/module/PartnerCenter/Get-PartnerInvoiceLineItem) command and pipe the results through [Export-Csv](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/export-csv) to generate a local copy of what is available in the portal. 

Do you think this a good approach instead of having a command that provides this in a single step?

**Comment by AleixPerez** [comment]
Hi @isaiahwilliams,

Yes, I think is a good approach, I guess that this cmdlet not export the iur data, but I could checked that its exported also.

Thank you

**Comment by isaiahwilliams** [comment]
When you say IUR are you talking about Azure Partner Shared Services? Or the benefits you get from the MPN program?

Isaiah Williams
________________________________

**Comment by isaiahwilliams** [comment]
Hi @AleixPerez, 

Please let us know if you have any additional questions.
