### ISSUE TITLE
End Time provided but can't be seem by api

### ISSUE THREAD

**Issue by Crazyabout** [Microsoft/Partner-Center-PowerShell#86]
I tried folowing rest call exactly like in the microsoft docs but the error says that i don't provided an end time. The end time is provided and is a valid format. Does anyone see if this is my fault , or a bug in the rest api ?
![image](https://user-images.githubusercontent.com/45975657/52867871-364b0700-3142-11e9-9843-fca0648669ab.png)

**Comment by isaiahwilliams** [comment]
Hi @Crazyabout, 

The reason you are encountering this error is that the address should look similar to 

https://api.partnercenter.microsoft.com/v1/customers/E499C962-9218-4DBA-8B83-8ADC94F47B9F/subscriptions/FC8F8908-F918-4406-AF13-D5BC0FE41865/utilizations/azure?start_time=2017-07-02T00:00:00-08:00&end_time=2017-08-02T00:00:00-08:00 

When you are making this request with the Partner Center PowerShell module you will want to use the [Get-PartnerCustomerSubscriptionUtilization](https://docs.microsoft.com/powershell/module/partnercenter/get-partnercustomersubscriptionutilization) command. 

The sample request in the document needs to be updated because it has &amp; when it should be &
